"""initial schema

Revision ID: 04120d239b3b
Revises: 
Create Date: 2026-04-21 02:13:45.481251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04120d239b3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'invoices', 'patients', ['patient_id'], ['id'])
    op.add_column('patients', sa.Column('name', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'age')
    op.drop_column('patients', 'name')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
