"""Add staff table and therapist_id

Revision ID: 601b77016fba
Revises: 5cfc70262f44
Create Date: 2026-04-20 20:17:10.954800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601b77016fba'
down_revision: Union[str, Sequence[str], None] = '5cfc70262f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('therapist', 'nurse', 'admin', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('appointments', sa.Column('therapist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'staff', ['therapist_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'services', ['name'])
    op.add_column('session_notes', sa.Column('therapist_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'session_notes', 'staff', ['therapist_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_notes', type_='foreignkey')
    op.drop_column('session_notes', 'therapist_id')
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'therapist_id')
    op.drop_table('staff')
    # ### end Alembic commands ###
